### ISSUE TITLE
Spike: Integration of reactronica into midi-bricks

### ISSUE THREAD

**Issue by TimSusa** [unkleho/reactronica#22]
Hi, 

I stumbled over your repo. As I am the guy behind midi-bricks, I will consider integration of your components into my app. Is that a okay for you? By the way I am not making money with it. 

https://github.com/TimSusa/cliptor

https://github.com/TimSusa/midi-bricks

Best Regards 

Tim Susa

**Comment by unkleho** [comment]
Hey sorry for the late reply. No worries, look forward see what you do with it.
