### ISSUE TITLE
TS7016: Could not find a declaration file for module 'reactronica'

### ISSUE THREAD

**Issue by markjamesm** [unkleho/reactronica#38]
Attempting to convert a simple project from Javascript to Typescript results in the following error:
![err](https://user-images.githubusercontent.com/20845425/147412048-43a89581-cd67-423e-b015-964fd98f868a.jpg)

Would it be possible to add the types to the npm registry?

**Comment by markjamesm** [comment]
Just a note, following [this guide](https://www.newline.co/@bespoyasov/how-to-declare-missing-types-for-external-libraries--ff45540d) fixed my issues. Inside @types/reactronica/ I created a new file index.d.ts and added the following code:
`declare module 'reactronica'`

I was able to build the project after this.

**Comment by unkleho** [comment]
Reactronica is written in TS, so types should be okay. Do you have a Codesandbox or Stackblitz example to checkout?

**Comment by markjamesm** [comment]
> Reactronica is written in TS, so types should be okay. Do you have a Codesandbox or Stackblitz example to checkout?

I haven't used those, but here are my steps to reproduce the bug:

1. Create a new app using the Reactronica template `npx create-react-app test-typescript --template reactronica`
2. Navigate to the new directory and install TypeScript using `npm install --save typescript @types/node @types/react @types/react-dom @types/jest` 
3. Create tsconfig.json and add the following:
`{
  "compilerOptions": {
    "target": "es2017",
    "lib": [
      "dom",
      "dom.iterable",
      "esnext"
    ],
    "allowJs": true,
    "skipLibCheck": true,
    "esModuleInterop": true,
    "allowSyntheticDefaultImports": true,
    "strict": true,
    "forceConsistentCasingInFileNames": true,
    "module": "esnext",
    "moduleResolution": "node",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "noEmit": true,
    "jsx": "react",
  },
  "include": [
    "src"
  ]
}`
4. Rename App.js to App.tsx
5. Finally, run `npm start` and the following error occurs:
![builderror](https://user-images.githubusercontent.com/20845425/147418117-f0c9f717-1cb6-4154-a222-bc7bbdc89ed0.jpg)

Trying the `npm i --save-dev @types/reactronica` (what npm suggests) results in a 404 not found error:
`PS C:\Users\mjmcd\Desktop\Programming Projects\test-typescript> npm i --save-dev @types/reactronica
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@types%2freactronica - Not found
npm ERR! 404
npm ERR! 404  '@types/reactronica@*' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.`

In some additional tests, I discovered I can resolve this issue by adding `"noImplicitAny": false` to the tsconfig.json above and the solution builds without error.

**Comment by unkleho** [comment]
Hi thanks for the steps. I've recreated and can confirm that the create react app template has an old version of Reactronica. Updating to 0.7.0 should do the trick. @types/reactronica doesn't exist because we already have types in this library.

I'll have to update the CRA template when I get a chance.
