### ISSUE TITLE
Feature Request: DAW Example Code

### ISSUE THREAD

**Issue by ClaireBookworm** [unkleho/reactronica#45]
It'd be awesome if you could share the code for your DAW ([reactronica.com/daw](https://reactronica.com/daw)) example as a reference. Thank you!

**Comment by unkleho** [comment]
Hi Claire, it is in a previous tag:
https://github.com/unkleho/reactronica/blob/v0.4.6/website/components/DAWApp/DAWApp.tsx

Cheers!
